export const HEADER_NAVIGATION_LOAD_START = 'HEADER_NAVIGATION_LOAD_START'
export const HEADER_NAVIGATION_LOAD_END = 'HEADER_NAVIGATION_LOAD_END'
export const BASE_SIZE_RESIZE = 'BASE_SIZE_RESIZE'
export const UPDATE_HEADER = 'UPDATE_HEADER'
